export const INCIDENTS = [
  {
    id: "INC-001",
    type: "Road Accident",
    loc: "Ring Road / Iwo Rd Junction",
    city: "Ibadan",
    time: "2 min ago",
    raw: 2,
    conf: 92,
    witnesses: 4,
    status: "active",
    dist: "0.8 km",
    priority: "high",
    responder: null,
  },
  {
    id: "INC-002",
    type: "Medical Emergency",
    loc: "UI Campus, Gate 1",
    city: "Ibadan",
    time: "8 min ago",
    raw: 8,
    conf: 78,
    witnesses: 1,
    status: "active",
    dist: "2.4 km",
    priority: "medium",
    responder: "Dr. Ade Okonkwo",
  },
  {
    id: "INC-003",
    type: "Road Accident",
    loc: "Lagos-Ibadan Expressway, KM 12",
    city: "Ibadan",
    time: "15 min ago",
    raw: 15,
    conf: 85,
    witnesses: 3,
    status: "routing",
    dist: "4.1 km",
    priority: "high",
    responder: "UI Teaching Hospital",
  },
  {
    id: "INC-004",
    type: "Road Accident",
    loc: "Challenge Roundabout",
    city: "Ibadan",
    time: "34 min ago",
    raw: 34,
    conf: 61,
    witnesses: 2,
    status: "responded",
    dist: "6.3 km",
    priority: "low",
    responder: "Jericho Specialist",
  },
  {
    id: "INC-005",
    type: "Fire Hazard",
    loc: "Bodija Market, Block C",
    city: "Ibadan",
    time: "1 hr ago",
    raw: 60,
    conf: 44,
    witnesses: 1,
    status: "resolved",
    dist: "3.2 km",
    priority: "low",
    responder: "LASEMA",
  },
  {
    id: "INC-006",
    type: "Medical Emergency",
    loc: "Agodi Estate, Entrance",
    city: "Ibadan",
    time: "2 hr ago",
    raw: 120,
    conf: 89,
    witnesses: 2,
    status: "resolved",
    dist: "5.5 km",
    priority: "high",
    responder: "State Hospital",
  },
];

export type Incident = (typeof INCIDENTS)[0];

export const confColor = (c: number) =>
  c >= 75 ? "var(--green)" : c >= 50 ? "var(--amber)" : "var(--red)";

export const statusBadge: Record<string, string> = {
  active: "badge-red",
  routing: "badge-amber",
  responded: "badge-green",
  resolved: "badge-dim",
};

export const MAP_PINS = [
  { ...INCIDENTS[0], x: 38, y: 29 },
  { ...INCIDENTS[1], x: 62, y: 50 },
  { ...INCIDENTS[2], x: 21, y: 65 },
  { ...INCIDENTS[3], x: 74, y: 38 },
  { ...INCIDENTS[4], x: 50, y: 72 },
  {
    x: 55, y: 28,
    id: "HOSP-1", type: "Hospital",
    loc: "UI Teaching Hospital",
    status: "ready", conf: 100, witnesses: 0,
    city: "", time: "", raw: 0, dist: "", priority: "", responder: null,
  },
  {
    x: 78, y: 56,
    id: "HOSP-2", type: "Hospital",
    loc: "Jericho Specialist",
    status: "ready", conf: 100, witnesses: 0,
    city: "", time: "", raw: 0, dist: "", priority: "", responder: null,
  },
];